apiVersion: v1
kind: Namespace
metadata:
  name: sri1

---

apiVersion: v1
kind: Pod
metadata:
  namespace: sri1
  name: sripython
spec:
  containers:
  - name: sripython
    image: ssreee/helloworld-demo-python:v1
    ports:
    - containerPort: 8080


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssreee-deployment
  namespace: sri1
  labels:
    app: python
spec:
  replicas: 7
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: ssreee
        image: ssreee/helloworld-demo-python:v1
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
 name: my-service
 namespace: sri1
spec:
 type: NodePort
 selector:
   app: python
 ports:
   - port: 8080
     # By default and for convenience, the `targetPort` is set to
     # the same value as the `port` field.
     targetPort: 8080
     # Optional field
     # By default and for convenience, the Kubernetes control plane
     # will allocate a port from a range (default: 30000-32767)
     nodePort: 30007
