name: docker-ci-pipeline
on: push
jobs:
  docker-ci-jon:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        
      - name: Build Image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1 .
        
      - name: Verify Image
        run: docker images
        
      - name: docker login
        uses: docker/login-action@v3.6.0
        with:
          username:  ${{ vars.DOCKER_USERNAME }}
          password:  ${{ secrets.DOCKER_SECRET_NAME }}
          
      - name: Push Image to hub
        run: docker push ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1 .
       
