name: docker-ci-pipeline
on: 
  push: 
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - '/sample'
jobs:
  docker-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        
      - name: Build Image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1 .
        
      - name: Verify Image
        run: docker images

      - name: create container
        run: docker run --name python-app -itd -p 8080:8080 ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1

      - name: sleep time to create container
        run: sleep 20

      - name: verify container status
        run: docker ps -a

      - name: verify the URL
        run: curl http://localhost:8080

      - name: docker login
        uses: docker/login-action@v3.6.0
        with:
          username:  ${{ vars.DOCKER_USERNAME }}
          password:  ${{ secrets.DOCKER_SECRET_NAME }}
          
      - name: Push Image to hub
        run: docker push ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1
       
      - name: Cleanup
        run: docker rm -f python-app

 k8s-cd-job:
    needs: docker-ci-job
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: setup-minikube
        uses: medyagh/setup-minikube@latest

      - name: Check minikube
        run:  kubectl get pods -A

      - name: set namespace
        run:  kubectl config set-contect --current --namespace=sri1

      - name:  create deployment
        run:  kubectl apply -f k8s/.

      - name:  wait for pod creation
        run: kubectl wait --for=condition=ready pod -l app=python

      - name:  get status deployment
        run:  kubectl get ns,deploy,service -n app=python

      - name:  Test URL
        run:  minikube service list
              minikube service my-service --url
              echo -n "------------------opening the service------------------"
              curl $(minikube service my-service --url)/version              

